import React from 'react';
import Container from 'react-bootstrap/Container';
import './TermsAndConditions.css';


const TermsAndConditions = () => {
    return (
        <div className="TermsAndConditions">
            <Container>
                <div className="TermsAndConditions-container">
                    <Container>
                        <h2>Terms & Conditions</h2>

                        <p><strong>Your details</strong></p>
                        <ol>
                            <li>When you register with The Book Shelf website, you will be required to choose a contact email address and password. You are responsible for all sessions and transactions made using these details. You should keep your password safe and not disclose it to anyone. You should change it immediately if you feel it has been compromised.</li>
                            <br />
                            <li>If any of your details change, such as your credit card billing address, you must inform The Book Shelf as soon as possible. You may update your details by signing into your account on The Book Shelf website, and updating your online wallet.</li>
                        </ol>
                        <p><strong>The contract between us</strong></p>
                        <ol>
                            <li>Any contract for purchases made through The Book Shelf website will be with The Book Shelf Limited (company registration number 5124926) whose registered office is situated at 1 Principal Place, Worship Street, London, EC2A 2FA . Our VAT registration numbers are listed in the Value Added Tax (VAT) section below.</li>
                            <br />
                            <li>The Book Shelf must receive payment of the whole of the price for the goods that you order before your order can be processed. Payment of the advertised price will be taken at the point of order. Charging your payment method does not mean that an order has been accepted by The Book Shelf. Once payment has been processed, The Book Shelf will confirm that your order has been received by sending an email to you at the email address you provide. The email will include your name, the order number and the total price charged. The Book Shelf acceptance of your order (which will happen when The Book Shelf dispatches your order) brings into existence a legally binding contract between us on these terms. Any term sought to be imposed by you in your order will not form part of the contract.</li>
                            <br />
                            <li>The Book Shelf will not process any orders in the case of errors or inaccuracies regarding the goods (including the advertised price of the goods) appearing on our website. If an error or inaccuracy is discovered with regards to the advertised price of the goods that you have ordered, we will contact you as soon as possible by email and reserve the right to cancel your order.</li>
                            <br />
                            <li>This Site is strictly for personal and non-commercial use. You agree not to use the site for commercial or business purposes or to place orders which will be, or are being, sold on to a third party. If you are suspected of using the site in any of these ways then we reserve the right to withdraw from any relevant contract(s) and cancel your order(s).</li>
                        </ol>
                        <p><strong>Your right of cancellation</strong></p>
                        <ol>
                            <li>You will be responsible for the cost of returning the item to us, unless we delivered it to you in error or it is faulty. You must send the item back to us no later than 14 days from the day on which you notified us of your cancellation, by following the instructions we send you.</li>
                            <br />
                            <li>We will refund the price of the item no later than 14 days from the day on which we receive the item back from you or, if earlier, the day on which you provide evidence reasonably acceptable to us that you have sent the item back. We'll refund the same means of payment as you used to make your purchase.</li>
                        </ol>
                        <p><strong>Availability of goods you order</strong> If The Book Shelf has insufficient stock to deliver the goods ordered by you, or cannot obtain the stock from our suppliers, we will notify you as soon as possible and any sum debited by The Book Shelf from your payment method will be credited to your account and The Book Shelf will notify you by email at the address given by you in your order form. The refund will be made as soon as possible and in any event within 30 days of your order. The Book Shelf will not be obliged to offer any additional compensation or to supply the goods in this situation. Please note: we endeavour to bring our customers the best value we can by running special offers, but please remember stocks are limited at the special offer price, and subject to availability. We update our website as quickly as we can to minimise disappointment. The process of updating the website when goods have sold out at promotional price may take a few hours. Please note that the price the goods are offered for are as displayed in your online basket, but that is subject to the rest of these terms.</p>
                        <p> <strong>Multi-buy offers</strong> Promotions apply to listed titles only, which are subject to change and availability. If you choose to purchase a product from a multi-buy offer, but do not purchase enough products to qualify for the special discount, the product will be charged at the normal price. Please note that on 3 for 2 promotions (and other multi-buy offers), the lowest priced title will always be the 'free' item. </p>
                        <p><strong>Delivery of goods to you</strong> The Book Shelf will post, or arrange a courier on your behalf, for the goods ordered by you to the person and address you give The Book Shelf at the time you make your order. Delivery will be made as soon as possible after your order is accepted and in any event within 30 days of dispatch of the order. All delivery times quoted on the web site are estimates only, based on availability, normal processing and delivery companies. You will become the owner of the goods you have ordered when the goods are dispatched to you from our distribution centre.</p>
                        <p><strong>Value Added Tax (VAT)</strong> All prices displayed on The Book Shelf website are inclusive of your local Tax (or applicable local sales tax, VAT and similar taxes). Your final price may be different depending upon the tax that applies to your delivery location. Where The Book Shelf apply a different tax rate based on the destination of the goods, this will be declared in the checkout.  When ordering goods from The Book Shelf for delivery overseas, you may be subject to import duties and taxes that are levied once the package reaches your country. Any additional charges for customs clearance must be borne by you; we have no control over these charges and cannot predict what they may be.   Customs policies vary widely from country to country, so you should contact your local customs office for further information. Additionally, please note that when ordering from The Book Shelf, you are considered the importer of record and must comply with all laws and regulations of the country in which you are receiving the goods.  <strong>VAT registration numbers</strong> <span>Austria 437/4614</span> <span>Belgium BE 0842 561 893</span> <span>Bulgaria BG3075132408</span> <span>Croatia HR16379598282</span> <span>Cyprus CY99200052Z</span> <span>Czech Republic CZ683052523</span> <span>Denmark DK12641915</span> <span>Estonia EE101519487</span> <span>Finland FI24504502</span> <span>France 79 498136506</span> <span>Germany 252 8258 94</span> <span>Greece EL997542198</span> <span>Hungary HU26908355</span> <span>Ireland IE9811968B</span> <span>Italy IT00146599998</span> <span>Latvia LV90009697727</span> <span>Lithuania LT100006871218</span> <span>Luxembourg LU25128942</span> <span>Malta MT20619027</span> <span>Netherlands NL823500962B01</span> <span>New Zealand 130-500-501</span> <span>Portugal PT980464315</span> <span>Poland PL5263087768</span> <span>Romania RO30232444</span> <span>Slovakia SK4020351170</span> <span>Spain N8262632F</span> <span>Sweden SE502070939901</span> <span>UK 840 3399 30</span> <span>ABN number: 19 824 886 404 <span>New Zealand GST number: 130-500-501</span> </span></p>
                        <p><strong>Liability</strong> This is as follows:</p>
                        <ol>
                            <li> If the goods The Book Shelf delivers are not what you ordered or are damaged or defective or the delivery is of an incorrect quantity, The Book Shelf shall have no liability to you unless you notify The Book Shelf in writing at The Book Shelf contact address of the problem within ten working days of the delivery of goods in question.</li>
                            <br />
                            <li>If you do not receive goods ordered by you within 30 days of the date on which they were dispatched to you, The Book Shelf shall have no liability to you unless you notify The Book Shelf in writing at The Book Shelf contact address of the problem within 40 days of the date on which the goods were dispatched to you.</li>
                            <br />
                            <li>If you notify a problem to The Book Shelf under this condition, The Book Shelf only obligation will be, at its option, to make good any shortage or non-delivery; to replace or repair any goods that are damaged or defective; or to refund to you the amount paid by you for the goods in question to the original method of payment, unless such method is no longer valid in which case The Book Shelf e-coupons will be issued to the value of the refund due.</li>
                            <br />
                            <li>The Book Shelf will not be liable to you for any indirect or consequential loss or damage arising out of any problem you notify to The Book Shelf under this condition and The Book Shelf shall have no liability to pay any money to you by way of compensation other than to refund to you the amount paid by you for the goods in question under paragraph (c) above.</li>
                            <br /><li>Nothing in this condition is, however, intended to limit any rights you might have as a consumer under applicable local law that may not be excluded nor in any way to exclude or limit The Book Shelf liability to you for any death or personal injury resulting from its negligence.</li>
                        </ol>
                        <p>Nothing in this contract creates any right which is enforceable by any person who is not a party to the contract.</p>
                        <p> <strong>Force Majeure</strong> The Book Shelf shall have no liability to you for any failure to deliver goods you have ordered or any delay in doing so or for any damage or defect to goods delivered that is caused by any event or circumstance beyond its reasonable control. </p>
                        <p><strong>Invalidity</strong> If any part of these conditions is unenforceable (including any provision in which The Book Shelf excludes its liability to you) the enforceability of any other part of these conditions will not be affected. </p>
                        <p><strong>Complaints</strong> The Book Shelf operates a complaints handling procedure which is used to try to resolve disputes when they first arise. If you have a complaint, please contact the Customer Service department at the following address: Customer Service Manager, The Book Shelf Limited, Gateway 12 Business Park, Davy Way, Gloucester, Gloucestershire. </p>
                        <p><strong>Governing Law</strong> The contract between us shall be governed by and interpreted in accordance with English law, and the English courts shall have jurisdiction to resolve any disputes between us. If you reside in the European Union, the European Commission provides for an online dispute resolution platform, which you can access here: http://ec.europa.eu/consumers/odr/. If you would like to bring a matter to our attention, please email us at help@support.bookdepository.com. </p>
                        <p><strong>Entire Agreement</strong> These terms and conditions, together with the current The Book Shelf website prices, delivery details and The Book Shelf contact details, set out the whole of our agreement relating to the supply of the goods to you by The Book Shelf. These terms and conditions cannot be varied except in writing signed by a director of The Book Shelf. In particular nothing said by any sales person on behalf of The Book Shelf should be understood as a variation of these terms and conditions or as an authorised representation about the nature or quality of any goods offered for sale by The Book Shelf. The Book Shelf shall have no liability for any such representation being untrue or misleading. </p>
                        <p><strong>Disclaimer</strong> The nature of Internet communications means that your communications may be susceptible to data corruption, interception and delays. The Book Shelf shall not be responsible for any detrimental reliance you place on this website or its contents. The Book Shelf is providing this site and its contents (including any downloadable data or software) on an 'as is' basis and makes no representations or warranties of any kind with respect to this site or its contents and disclaims all such representations and warranties, whether express or implied, to the fullest extent permitted by applicable law. In addition, The Book Shelf makes no representations or warranties about the accuracy, completeness or suitability for any particular purpose of the information and related graphics published in this site or that any software or the server that makes it available are free of viruses or other harmful components. The information contained in this site may contain technical inaccuracies or typographical errors. All liability of The Book Shelf howsoever arising for any such inaccuracies or errors is expressly excluded to the fullest extent permitted by applicable law. Neither The Book Shelf nor any of its Directors, employees or other representatives will be liable for damages arising out of or in connection with the use of this site in any way. This is a comprehensive limitation of liability that applies to all damages of any kind, including (without limitation) compensatory, direct, indirect or consequential damages, loss of data, income or profit, loss of or damage to property and claims of third parties. </p>
                        <p><strong>Hyperlinks</strong> Our website may contain hyperlinks. These hyperlinks connect you to sites of other organisations which are not our responsibility. We have used our reasonable endeavours in preparing our own website and the information included in it is done so in good faith. However, we have no control over any of the information you can access via other websites. Therefore, no mention of any organisation, company or individual to which our website is linked shall imply any approval or warranty as to the standing and capability of any such organisations, company or individual on the part of The Book Shelf. </p>
                        <p><strong>Copyright notice</strong> All design, text, graphics and the selection or arrangement thereof are the copyright of The Book Shelf, or of other copyright owners. Permission is granted to electronically copy and print in hard copy portions of this site for the sole purpose of placing an order with The Book Shelf, or using this site as a shopping resource. Any other use of materials on this site (including reproduction for purposes other than those noted above and modification, distribution, or republication) without the prior written permission of The Book Shelf is strictly prohibited. </p>
                        <p><strong>Trade marks</strong> The Book Shelf and The Book Shelf logo are registered trademarks belonging to The Book Shelf Limited. All other trademarks, product names and company names or logos used in this site are the property of their respective owners. No permission is given by The Book Shelf in respect of the use of its or any such other trademarks, product names, titles or logos and such use may constitute an infringement of the holder's rights. </p>
                        <p><strong>Submitting text for publication on The Book Shelf.co.uk</strong></p>
                        <ul>
                            <li> Users of our site may submit material for publication in various areas of the site (e.g. reviews and comments). We accept no liability in respect of any material submitted by users and published by us and we are not responsible for its content and accuracy. </li>
                            <br />
                            <li>If you want to submit material to us for publication on The Book Shelf.com, you may do so on the following terms and conditions: </li>
                            <br />
                            <li>Publication of any material you submit to us will be at our sole discretion. We reserve the right to make additions or deletions to the text or graphics prior to publication, or to refuse publication </li>
                            <br />
                            <li>You warrant to us that any material you submit to us is your own original work and that you own the copyright and any other relevant rights </li>
                            <br />
                            <li>You warrant that the material you submit is not obscene, offensive, defamatory of any person or otherwise illegal </li>
                            <br />
                            <li>You agree not to post material which is deliberately intended to upset other users </li>
                            <br />
                            <li>You acknowledge that any breach of these warranties may cause us damage or loss and you agree to indemnify us in full and permanently against any third party liabilities, claims, costs, loss or damage we incur as a result of publishing material you submit to us, including consequential losses. </li>
                            <br /><li>We reserve the right to remove your access to individual services completely if we believe you are abusing the services in any way. </li>
                        </ul>
                        <p><strong>Interpretation</strong> In these terms and conditions:- 'The Book Shelf' means The Book Shelf Limited, 1 Principal Place, Worship Street, London, EC2A 2FA any connected organisation that actually supplies goods ordered by you and any successor to its business; 'working day' means every day of a calendar year apart from weekends and statutory and public holidays; 'us' means The Book Shelf and you together; and 'you' and 'your' means the person ordering goods under these terms and conditions.</p>
                    </Container>
                </div>
            </Container>
        </div>
    )
};
export default TermsAndConditions;
